import heroImage from "../assets/images/card-image.png"

export default [
    {
        id: 1,
        title: 'BLKcard Freedom Unlimited Credit Card',
        image: heroImage,
        offerHeading: 'new cardmember offer',
        offerText: 'Earn a $200 bonus after you spend $500 on purchases in the first 3 months from account opening.',
        glanceHeader: 'at a glance',
        glanceText: `Earn cash back for every purchase. Earn unlimited 1.5% cash back or more on all purchases,
         like 3% on dining and drugstores and 5% on travel purchased through BLKcard.`,
        aprHeader: 'apr',
        aprText: `0% intro APR for 15 months from account opening on purchases and balance transfers. After the intro period,
        a variable APR of 19.99%-28.74%. Balance transfer fee applies, see pricing and terms for more details.`,
        annualFeeHeader: 'annual fee',
        annualFeeText: '$25' 
    },
    {
        id: 2,
        title: 'BLKcard Freedom Flex Credit Card',
        image: heroImage,
        offerHeading: 'new cardmember offer',
        offerText: 'Earn a $200 bonus after you spend $500 on purchases in the first 3 months from account opening.',
        glanceHeader: 'at a glance',
        glanceText: `Earn cash back for every purchase. Earn unlimited 1.5% cash back or more on all purchases,
         like 3% on dining and drugstores and 5% on travel purchased through BLKcard.`,
        aprHeader: 'apr',
        aprText: `0% intro APR for 15 months from account opening on purchases and balance transfers. After the intro period,
        a variable APR of 19.99%-28.74%. Balance transfer fee applies, see pricing and terms for more details.`,
        annualFeeHeader: 'annual fee',
        annualFeeText: '$50' 
    },
    {
        id: 3,
        title: 'BLKcard Freedom Student Credit Card',
        image: heroImage,
        offerHeading: 'new cardmember offer',
        offerText: 'Earn a $200 bonus after you spend $500 on purchases in the first 3 months from account opening.',
        glanceHeader: 'at a glance',
        glanceText: `Earn cash back for every purchase. Earn unlimited 1.5% cash back or more on all purchases,
         like 3% on dining and drugstores and 5% on travel purchased through BLKcard.`,
        aprHeader: 'apr',
        aprText: `0% intro APR for 15 months from account opening on purchases and balance transfers. After the intro period,
        a variable APR of 19.99%-28.74%. Balance transfer fee applies, see pricing and terms for more details.`,
        annualFeeHeader: 'annual fee',
        annualFeeText: '$0' 
    },
    {
        id: 4,
        title: 'BLKcard Silver Preferred Credit Card',
        image: heroImage,
        offerHeading: 'new cardmember offer',
        offerText: 'Earn a $200 bonus after you spend $500 on purchases in the first 3 months from account opening.',
        glanceHeader: 'at a glance',
        glanceText: `Earn cash back for every purchase. Earn unlimited 1.5% cash back or more on all purchases,
         like 3% on dining and drugstores and 5% on travel purchased through BLKcard.`,
        aprHeader: 'apr',
        aprText: `0% intro APR for 15 months from account opening on purchases and balance transfers. After the intro period,
        a variable APR of 19.99%-28.74%. Balance transfer fee applies, see pricing and terms for more details.`,
        annualFeeHeader: 'annual fee',
        annualFeeText: '$0' 
    },
    {
        id: 5,
        title: 'BLKcard Gold Preferred Credit Card',
        image: heroImage,
        offerHeading: 'new cardmember offer',
        offerText: 'Earn a $200 bonus after you spend $500 on purchases in the first 3 months from account opening.',
        glanceHeader: 'at a glance',
        glanceText: `Earn cash back for every purchase. Earn unlimited 1.5% cash back or more on all purchases,
         like 3% on dining and drugstores and 5% on travel purchased through BLKcard.`,
        aprHeader: 'apr',
        aprText: `0% intro APR for 15 months from account opening on purchases and balance transfers. After the intro period,
        a variable APR of 19.99%-28.74%. Balance transfer fee applies, see pricing and terms for more details.`,
        annualFeeHeader: 'annual fee',
        annualFeeText: '$100' 
    },
    {
        id: 6,
        title: 'BLKcard Platinum Preferred Credit Card',
        image: heroImage,
        offerHeading: 'new cardmember offer',
        offerText: 'Earn a $200 bonus after you spend $500 on purchases in the first 3 months from account opening.',
        glanceHeader: 'at a glance',
        glanceText: `Earn cash back for every purchase. Earn unlimited 1.5% cash back or more on all purchases,
         like 3% on dining and drugstores and 5% on travel purchased through BLKcard.`,
        aprHeader: 'apr',
        aprText: `0% intro APR for 15 months from account opening on purchases and balance transfers. After the intro period,
        a variable APR of 19.99%-28.74%. Balance transfer fee applies, see pricing and terms for more details.`,
        annualFeeHeader: 'annual fee',
        annualFeeText: '$200' 
    },
]